
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import os

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage





def disable_event():
   pass
ASSETS_PATH = Path(r"assets\frame2")

def kclose():
    os.system("main.exe")
    foto.destroy
def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


foto = Tk()

foto.geometry("1920x1080")
foto.configure(bg = "#FFFFFF")


canvas = Canvas(
    foto,
    bg = "#FFFFFF",
    height = 1080,
    width = 1920,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: kclose(),
    relief="flat"
)
button_1.place(
    x=1697.0,
    y=18.0,
    width=212.0,
    height=161.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    960.0,
    540.0,
    image=image_image_1
)
foto.resizable(False, False)
foto.wm_attributes('-toolwindow', 'True')

foto.protocol("WM_DELETE_WINDOW", disable_event)
foto.mainloop()
