i = 0
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import shutil
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import os
import tkinter as tk
import time
def disable_event():
    pass
alph = ''
def keypad():
    #keypad
    print("Startuju keypad")
    window = Tk()
    print("keypad")
    
    OUTPUT_PATH = Path(__file__).parent
    print()
    Ahoj =r"assets\frame0"
    ASSETS_PATH =Path(Ahoj)
    print(f"{OUTPUT_PATH} / {Ahoj} =  {ASSETS_PATH}")

    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)
    


    def clic(i):
        global alph
        i = str(i)
        alph = alph + i
        print(alph)
        if i == "5":
            alph = ""
        if alph == '8241':
            window.destroy()

    

    window.geometry("431x589")
    window.title('keypad')
    logo = tk.PhotoImage(file=Path(r"assets\4436481.png"))
    window.call('wm', 'iconphoto', window._w, logo)
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 589,
        width = 431,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    print("pred obrazkem")
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    print(relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        215.0,
        294.0,
        image=image_image_1
    )


    canvas.create_rectangle(
        -1.0,
        182.0,
        431.0,
        184.0,
        fill="#01CFFF",
        outline="")

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:clic(1),
        relief="flat"
    )
    button_1.place(
        x=35.0,
        y=197.0,
        width=77.0,
        height=109.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:clic(8),
        relief="flat"
    )
    button_2.place(
        x=341.0,
        y=300.0,
        width=77.0,
        height=106.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:clic(7),
        relief="flat"
    )
    button_3.place(
        x=247.0,
        y=300.0,
        width=77.0,
        height=106.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:clic(6),
        relief="flat"
    )
    button_4.place(
        x=130.0,
        y=300.0,
        width=77.0,
        height=106.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:clic(5),
        relief="flat"
    )
    button_5.place(
        x=35.0,
        y=300.0,
        width=77.0,
        height=106.0
    )

    button_image_6 = PhotoImage(
        file=relative_to_assets("button_6.png"))
    button_6 = Button(
        image=button_image_6,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:clic(4),
        relief="flat"
    )
    button_6.place(
        x=341.0,
        y=201.0,
        width=77.0,
        height=105.0
    )

    button_image_7 = PhotoImage(
        file=relative_to_assets("button_7.png"))
    button_7 = Button(
        image=button_image_7,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:clic(3),
        relief="flat"
    )
    button_7.place(
        x=247.0,
        y=201.0,
        width=77.0,
        height=105.0
    )

    button_image_8 = PhotoImage(
        file=relative_to_assets("button_8.png"))
    button_8 = Button(
        image=button_image_8,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:clic(2),
        relief="flat"
    )
    button_8.place(
        x=130.0,
        y=197.0,
        width=77.0,
        height=109.0
    )
    window.resizable(False, False)
    window.protocol("WM_DELETE_WINDOW", disable_event)
    window.wm_attributes('-toolwindow', 'True')
    window.mainloop()
    print("quitting")

def menu():
    
    ASSETS_PATH= r"assets\frame1"
    ASSETS_PATH = Path(ASSETS_PATH)


    def relative_to_assets(path: str) -> Path:
        print(ASSETS_PATH / Path(path))
        return ASSETS_PATH / Path(path)
    

    menu = Tk()
    def next_menu():
        menu.destroy()
        keypad()
        
    
    
    
    
    from subprocess import Popen, PIPE
    def kopn():
        
        menu.quit()
        
        Popen('kelly.exe')
        print("done")
    def updt():
        menu.quit()
        APPDATA = os.environ.get("USERPROFILE")
        PATH = Path(APPDATA)/r"KELLY\KELLY\update.exe"
        Popen(PATH)
        os.system(f"{PATH}")


    menu.geometry("450x584")
    logo = tk.PhotoImage(file=Path(r"assets\4436481.png"))
    menu.call('wm', 'iconphoto', menu._w, logo)
    menu.title('menu')
    menu.configure(bg = "#FFFFFF")


    canvas = Canvas(
        menu,
        bg = "#FFFFFF",
        height = 584,
        width = 450,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        225.0,
        292.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=27.0,
        y=266.0,
        width=167.0,
        height=52.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=207.0,
        y=516.0,
        width=221.0,
        height=52.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:next_menu(),
        relief="flat"
    )
    button_3.place(
        x=27.0,
        y=173.0,
        width=167.0,
        height=52.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:kopn(),
        relief="flat"
    )
    button_4.place(
        x=27.0,
        y=84.0,
        width=167.0,
        height=52.0
    )
    menu.resizable(False, False)
    menu.wm_attributes('-toolwindow', 'True')
    
    menu.protocol("WM_DELETE_WINDOW", disable_event)
    menu.mainloop()

if i <= 0:



    menu()
